/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FireMapRouteImport } from './routes/fire-map'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as SatelliteAnalysisRouteImport } from './routes/satellite-analysis'
import { Route as SatelliteMonitoringRouteImport } from './routes/satellite-monitoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FireMapRoute = FireMapRouteImport.update({
  id: '/fire-map',
  path: '/fire-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteAnalysisRoute = SatelliteAnalysisRouteImport.update({
  id: '/satellite-analysis',
  path: '/satellite-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteMonitoringRoute = SatelliteMonitoringRouteImport.update({
  id: '/satellite-monitoring',
  path: '/satellite-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/alerts': typeof AlertsRoute
  '/fire-map': typeof FireMapRoute
  '/history': typeof HistoryRoute
  '/satellite': typeof SatelliteRoute
  '/satellite-analysis': typeof SatelliteAnalysisRoute
  '/satellite-monitoring': typeof SatelliteMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/alerts': typeof AlertsRoute
  '/fire-map': typeof FireMapRoute
  '/history': typeof HistoryRoute
  '/satellite': typeof SatelliteRoute
  '/satellite-analysis': typeof SatelliteAnalysisRoute
  '/satellite-monitoring': typeof SatelliteMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/alerts': typeof AlertsRoute
  '/fire-map': typeof FireMapRoute
  '/history': typeof HistoryRoute
  '/satellite': typeof SatelliteRoute
  '/satellite-analysis': typeof SatelliteAnalysisRoute
  '/satellite-monitoring': typeof SatelliteMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/alerts'
    | '/fire-map'
    | '/history'
    | '/satellite'
    | '/satellite-analysis'
    | '/satellite-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/alerts'
    | '/fire-map'
    | '/history'
    | '/satellite'
    | '/satellite-analysis'
    | '/satellite-monitoring'
  id:
    | '__root__'
    | '/'
    | '/ai-analysis'
    | '/alerts'
    | '/fire-map'
    | '/history'
    | '/satellite'
    | '/satellite-analysis'
    | '/satellite-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalysisRoute: typeof AiAnalysisRoute
  AlertsRoute: typeof AlertsRoute
  FireMapRoute: typeof FireMapRoute
  HistoryRoute: typeof HistoryRoute
  SatelliteRoute: typeof SatelliteRoute
  SatelliteAnalysisRoute: typeof SatelliteAnalysisRoute
  SatelliteMonitoringRoute: typeof SatelliteMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fire-map': {
      id: '/fire-map'
      path: '/fire-map'
      fullPath: '/fire-map'
      preLoaderRoute: typeof FireMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite-analysis': {
      id: '/satellite-analysis'
      path: '/satellite-analysis'
      fullPath: '/satellite-analysis'
      preLoaderRoute: typeof SatelliteAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite-monitoring': {
      id: '/satellite-monitoring'
      path: '/satellite-monitoring'
      fullPath: '/satellite-monitoring'
      preLoaderRoute: typeof SatelliteMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalysisRoute: AiAnalysisRoute,
  AlertsRoute: AlertsRoute,
  FireMapRoute: FireMapRoute,
  HistoryRoute: HistoryRoute,
  SatelliteRoute: SatelliteRoute,
  SatelliteAnalysisRoute: SatelliteAnalysisRoute,
  SatelliteMonitoringRoute: SatelliteMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
